# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='mailchimp_id',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Mailchimp id'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
