# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='intro_tetx',
            field=models.TextField(default='', verbose_name='Introduction text'),
            preserve_default=False,
        ),
    ]
