# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 13:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_resource_intro_tetx'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='intro_tetx',
            new_name='intro_text',
        ),
    ]
