# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0008_auto_20170925_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='categories',
            field=models.ManyToManyField(related_name='resources', to='resources.Category', verbose_name='Categories'),
        ),
    ]
