# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 10:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0009_auto_20170925_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='text',
            new_name='full_text',
        ),
    ]
