# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 14:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0011_proposeresource_when_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposeresource',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.Category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='proposeresource',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
