# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-30 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0013_auto_20170929_1145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relatedresources',
            options={'ordering': ['primary', '-ranking'], 'verbose_name': 'Related resource', 'verbose_name_plural': 'Related resources'},
        ),
        migrations.AlterField(
            model_name='relatedresources',
            name='recommendation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.Resource', verbose_name='Related resource'),
        ),
    ]
