# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 20:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0014_auto_20170930_2031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='proposeresource',
            options={'verbose_name': 'Proposed resource', 'verbose_name_plural': 'Proposed resources'},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={'verbose_name': 'Resource', 'verbose_name_plural': 'Resources'},
        ),
    ]
